name: erdos-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - numpy=1.20.*
  - scipy=1.6.*
  - scikit-learn=0.24.*
  - statsmodels=0.12.*
  - pandas=1.2.*
  - matplotlib=3.4.*
  - seaborn=0.11.*
  - jupyterlab=3.0.*
  - bokeh=2.2.*